export const BlackRiver Gateway_RESPONSE_HEADERS = {
  cache: "X-BlackRiver Gateway-Cache",
  cacheHit: "X-BlackRiver Gateway-Cache-Hit",
  compression: "X-BlackRiver Gateway-Compression",
  costSaved: "X-BlackRiver Gateway-Cost-Saved",
  fallbackAttempts: "X-BlackRiver Gateway-Fallback-Attempts",
  latencyMs: "X-BlackRiver Gateway-Latency-Ms",
  model: "X-BlackRiver Gateway-Model",
  progress: "X-BlackRiver Gateway-Progress",
  provider: "X-BlackRiver Gateway-Provider",
  requestId: "X-BlackRiver Gateway-Request-Id",
  responseCost: "X-BlackRiver Gateway-Response-Cost",
  tokensIn: "X-BlackRiver Gateway-Tokens-In",
  tokensOut: "X-BlackRiver Gateway-Tokens-Out",
  version: "X-BlackRiver Gateway-Version",
} as const;
